"""initial schema

Revision ID: 0001_initial
Revises: 
Create Date: 2026-08-08
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0001_initial'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('detail', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('actor', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_entity_id'), 'audit_log', ['entity_id'], unique=False)
    op.create_table('integration_credentials',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('encrypted_payload', sa.LargeBinary(), nullable=False),
    sa.Column('connected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_ok_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider')
    )
    op.create_table('oauth_states',
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), nullable=False),
    sa.Column('code_verifier', sa.Text(), nullable=True),
    sa.Column('redirect_uri', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('state')
    )
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('etsy_receipt_id', sa.BigInteger(), nullable=False),
    sa.Column('order_number', sa.Text(), nullable=False),
    sa.Column('buyer_name', sa.Text(), nullable=True),
    sa.Column('placed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('shipstation_order_id', sa.BigInteger(), nullable=True),
    sa.Column('shipstation_last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('shipstation_attempts', sa.Integer(), nullable=False),
    sa.Column('tracking_number', sa.Text(), nullable=True),
    sa.Column('carrier_code', sa.Text(), nullable=True),
    sa.Column('service_code', sa.Text(), nullable=True),
    sa.Column('label_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('label_pdf', sa.LargeBinary(), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('new','in_production','assembly','ready_to_ship','shipped','cancelled')", name='ck_orders_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('etsy_receipt_id')
    )
    op.create_index('ix_orders_status', 'orders', ['status'], unique=False)
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('sku', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('fulfillment', sa.Text(), nullable=False),
    sa.Column('qbo_item_id', sa.Text(), nullable=True),
    sa.Column('qbo_item_name', sa.Text(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("fulfillment in ('printed','stocked','bundle')", name='ck_products_fulfillment'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_index('ix_products_sku_lower', 'products', [sa.text('lower(sku)')], unique=True)
    op.create_table('sync_log',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('job', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_log_job'), 'sync_log', ['job'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('bom_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('bundle_id', sa.Uuid(), nullable=False),
    sa.Column('component_id', sa.Uuid(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('bundle_id <> component_id', name='ck_bom_no_self_reference'),
    sa.CheckConstraint('quantity > 0', name='ck_bom_quantity_positive'),
    sa.ForeignKeyConstraint(['bundle_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['component_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bundle_id', 'component_id', name='uq_bom_bundle_component')
    )
    op.create_table('order_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.Uuid(), nullable=False),
    sa.Column('parent_line_id', sa.Uuid(), nullable=True),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('etsy_listing_id', sa.BigInteger(), nullable=True),
    sa.Column('etsy_transaction_id', sa.BigInteger(), nullable=True),
    sa.Column('sku_raw', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('qty_from_stock', sa.Integer(), nullable=False),
    sa.Column('qty_to_print', sa.Integer(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('override_state', sa.Text(), nullable=True),
    sa.Column('force_print', sa.Boolean(), nullable=False),
    sa.Column('assembled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stock_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('qty_from_stock >= 0', name='ck_order_lines_stock_nonneg'),
    sa.CheckConstraint('qty_to_print >= 0', name='ck_order_lines_print_nonneg'),
    sa.CheckConstraint('quantity > 0', name='ck_order_lines_quantity_positive'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_line_id'], ['order_lines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_lines_order_id'), 'order_lines', ['order_id'], unique=False)
    op.create_index(op.f('ix_order_lines_parent_line_id'), 'order_lines', ['parent_line_id'], unique=False)
    op.create_index(op.f('ix_order_lines_product_id'), 'order_lines', ['product_id'], unique=False)
    op.create_index('ix_order_lines_state', 'order_lines', ['state'], unique=False)
    op.create_table('print_mappings',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=False),
    sa.Column('bambuddy_archive_id', sa.Integer(), nullable=False),
    sa.Column('bambuddy_archive_name', sa.Text(), nullable=True),
    sa.Column('plate_number', sa.Integer(), nullable=False),
    sa.Column('units_per_plate', sa.Integer(), nullable=False),
    sa.Column('print_options', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('preferred_printer_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('plate_number > 0', name='ck_mapping_plate_positive'),
    sa.CheckConstraint('units_per_plate > 0', name='ck_mapping_units_per_plate_positive'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id')
    )
    op.create_table('print_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_line_id', sa.Uuid(), nullable=False),
    sa.Column('bambuddy_queue_id', sa.Integer(), nullable=True),
    sa.Column('bambuddy_archive_id', sa.Integer(), nullable=False),
    sa.Column('plate_number', sa.Integer(), nullable=True),
    sa.Column('printer_id', sa.Integer(), nullable=True),
    sa.Column('units_expected', sa.Integer(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('queued_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status in ('pending','queued','printing','done','failed','cancelled')", name='ck_print_jobs_status'),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_lines.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_print_jobs_order_line_id'), 'print_jobs', ['order_line_id'], unique=False)
    op.create_index('ix_print_jobs_status', 'print_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_print_jobs_status', table_name='print_jobs')
    op.drop_index(op.f('ix_print_jobs_order_line_id'), table_name='print_jobs')
    op.drop_table('print_jobs')
    op.drop_table('print_mappings')
    op.drop_index('ix_order_lines_state', table_name='order_lines')
    op.drop_index(op.f('ix_order_lines_product_id'), table_name='order_lines')
    op.drop_index(op.f('ix_order_lines_parent_line_id'), table_name='order_lines')
    op.drop_index(op.f('ix_order_lines_order_id'), table_name='order_lines')
    op.drop_table('order_lines')
    op.drop_table('bom_lines')
    op.drop_table('users')
    op.drop_index(op.f('ix_sync_log_job'), table_name='sync_log')
    op.drop_table('sync_log')
    op.drop_index('ix_products_sku_lower', table_name='products')
    op.drop_table('products')
    op.drop_index('ix_orders_status', table_name='orders')
    op.drop_table('orders')
    op.drop_table('oauth_states')
    op.drop_table('integration_credentials')
    op.drop_index(op.f('ix_audit_log_entity_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
