"""tls certificates

Revision ID: 0002_tls_certificates
Revises: 0001_initial
Create Date: 2026-08-08
"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = '0002_tls_certificates'
down_revision = '0001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tls_certificates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('cert_pem', sa.Text(), nullable=False),
    sa.Column('encrypted_key', sa.LargeBinary(), nullable=False),
    sa.Column('fingerprint_sha256', sa.Text(), nullable=False),
    sa.Column('common_name', sa.Text(), nullable=True),
    sa.Column('sans', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('not_before', sa.DateTime(timezone=True), nullable=True),
    sa.Column('not_after', sa.DateTime(timezone=True), nullable=True),
    sa.Column('self_signed', sa.Boolean(), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source in ('generated','uploaded')", name='ck_tls_source'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tls_certificates_active', 'tls_certificates', ['active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tls_certificates_active', table_name='tls_certificates')
    op.drop_table('tls_certificates')
    # ### end Alembic commands ###
